//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIndustry
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> SubIndustryId { get; set; }
    }
}
