//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExperience
    {
        public int ExpId { get; set; }
        public int UserId { get; set; }
        public string Designation { get; set; }
        public string CompanyName { get; set; }
        public string DurationFrom { get; set; }
        public string DurationTo { get; set; }
        public string Bio { get; set; }
        public string CompanyLogo { get; set; }
    }
}
