//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrokerMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEducation
    {
        public int EduId { get; set; }
        public int UserId { get; set; }
        public string UniversityName { get; set; }
        public string CourseName { get; set; }
        public string DurationFrom { get; set; }
        public string DurationTo { get; set; }
        public string EducationLogo { get; set; }
    }
}
